package com.example.erp.service;

import com.example.erp.entity.Employee;
import com.example.erp.entity.HrApplication;
import com.example.erp.exception.BadRequestException;
import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfWriter;
import org.springframework.stereotype.Service;

import java.io.File;
import java.io.FileOutputStream;
import java.time.LocalDate;
import java.time.LocalDateTime;

@Service
public class LeaveApprovalPdfService {

    private static final String PDF_DIR = "uploads/pdfs";

    public String generateLeaveApprovalPdf(HrApplication application, Employee employee) {
        if (!"Leave".equalsIgnoreCase(application.getType())) {
            return null;
        }

        if (!"Approved".equalsIgnoreCase(application.getStatus())) {
            throw new BadRequestException("PDF can be generated only for approved leave applications");
        }

        try {
            File directory = new File(PDF_DIR);
            if (!directory.exists()) {
                directory.mkdirs();
            }

            String filePath = PDF_DIR + "/leave-approval-" + application.getId() + ".pdf";

            Document document = new Document(PageSize.A4, 50, 50, 50, 50);
            PdfWriter.getInstance(document, new FileOutputStream(filePath));

            document.open();

            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18);
            Font headingFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12);
            Font normalFont = FontFactory.getFont(FontFactory.HELVETICA, 11);

            Paragraph title = new Paragraph("Leave Approval Letter", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            title.setSpacingAfter(20);
            document.add(title);

            Paragraph company = new Paragraph("HR ERP System", headingFont);
            company.setAlignment(Element.ALIGN_CENTER);
            company.setSpacingAfter(25);
            document.add(company);

            document.add(new Paragraph("Generated Date: " + LocalDate.now(), normalFont));
            document.add(new Paragraph("Application ID: " + application.getId(), normalFont));
            document.add(Chunk.NEWLINE);

            document.add(new Paragraph("Employee Details", headingFont));
            document.add(new Paragraph("Name: " + employee.getName(), normalFont));
            document.add(new Paragraph("Employee Code: " + employee.getEmployeeCode(), normalFont));
            document.add(new Paragraph("Department: " + safe(employee.getDepartment()), normalFont));
            document.add(new Paragraph("Designation: " + safe(employee.getDesignation()), normalFont));
            document.add(Chunk.NEWLINE);

            document.add(new Paragraph("Leave Details", headingFont));
            document.add(new Paragraph("Title: " + safe(application.getTitle()), normalFont));
            document.add(new Paragraph("Date Range: " + safe(application.getDateRange()), normalFont));
            document.add(new Paragraph("Number of Days: " + application.getDays(), normalFont));
            document.add(new Paragraph("Status: " + application.getStatus(), normalFont));
            document.add(new Paragraph("Manager Approval: " + application.getManagerStatus(), normalFont));
            document.add(new Paragraph("Admin Approval: " + application.getAdminStatus(), normalFont));
            document.add(Chunk.NEWLINE);

            document.add(new Paragraph("Approval Details", headingFont));
            document.add(new Paragraph("Reviewed By: " + safe(application.getReviewedBy()), normalFont));
            document.add(new Paragraph("Comment: " + safe(application.getReviewComment()), normalFont));
            document.add(Chunk.NEWLINE);

            Paragraph confirmation = new Paragraph(
                    "This document confirms that the leave request listed above has been reviewed and approved through the HR approval workflow.",
                    normalFont);
            confirmation.setSpacingBefore(10);
            confirmation.setSpacingAfter(30);
            document.add(confirmation);

            document.add(new Paragraph("Authorized HR Signature: ____________________", normalFont));
            document.add(Chunk.NEWLINE);
            document.add(new Paragraph("Generated by HR ERP System at " + LocalDateTime.now().withNano(0), normalFont));

            document.close();

            return filePath;

        } catch (Exception e) {
            throw new BadRequestException("Failed to generate leave approval PDF");
        }
    }

    private String safe(String value) {
        return value == null || value.isBlank() ? "-" : value;
    }
}