package com.example.erp.service;

import com.example.erp.entity.Employee;
import com.example.erp.entity.HrApplication;
import com.example.erp.exception.BadRequestException;
import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfWriter;
import org.springframework.stereotype.Service;

import java.io.File;
import java.io.FileOutputStream;
import java.time.LocalDate;
import java.time.LocalDateTime;

@Service
public class ReferenceLetterPdfService {

    private static final String PDF_DIR = "uploads/pdfs";

    public String generateReferenceLetterPdf(HrApplication application, Employee employee) {
        if (!"Reference Letter".equalsIgnoreCase(application.getType())) {
            return null;
        }

        if (!"Approved".equalsIgnoreCase(application.getStatus())) {
            throw new BadRequestException("PDF can be generated only for approved reference letter requests");
        }

        try {
            File directory = new File(PDF_DIR);
            if (!directory.exists()) {
                directory.mkdirs();
            }

            String filePath = PDF_DIR + "/reference-letter-" + application.getId() + ".pdf";

            Document document = new Document(PageSize.A4, 50, 50, 50, 50);
            PdfWriter.getInstance(document, new FileOutputStream(filePath));

            document.open();

            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18);
            Font headingFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12);
            Font normalFont = FontFactory.getFont(FontFactory.HELVETICA, 11);

            Paragraph title = new Paragraph("Employment Reference Letter", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            title.setSpacingAfter(20);
            document.add(title);

            Paragraph company = new Paragraph("HR ERP System", headingFont);
            company.setAlignment(Element.ALIGN_CENTER);
            company.setSpacingAfter(25);
            document.add(company);

            document.add(new Paragraph("Date: " + LocalDate.now(), normalFont));
            document.add(new Paragraph("Reference Request ID: " + application.getId(), normalFont));
            document.add(Chunk.NEWLINE);

            document.add(new Paragraph("To Whom It May Concern,", normalFont));
            document.add(Chunk.NEWLINE);

            Paragraph body = new Paragraph(
                    "This letter is to confirm that " + safe(employee.getName()) +
                            " is associated with our organization as " + safe(employee.getDesignation()) +
                            " in the " + safe(employee.getDepartment()) + " department. " +
                            "The employee record shows a joining date of " + safe(employee.getJoinDate()) +
                            " and current employment status as " + safe(employee.getStatus()) + ".",
                    normalFont);
            body.setSpacingAfter(15);
            document.add(body);

            Paragraph confirmation = new Paragraph(
                    "This reference letter has been generated after HR review and approval of the employee's request. "
                            + "HR/admin review comment: \""
                            + safe(application.getReviewComment())
                            + "\". "
                            + "This document is issued for official verification purposes only and should be used only by the intended recipient.",
                    normalFont);
            confirmation.setSpacingAfter(20);
            document.add(confirmation);

            document.add(new Paragraph("Employee Details", headingFont));
            document.add(new Paragraph("Employee Name: " + safe(employee.getName()), normalFont));
            document.add(new Paragraph("Employee Code: " + safe(employee.getEmployeeCode()), normalFont));
            document.add(new Paragraph("Email: " + safe(employee.getEmail()), normalFont));
            document.add(new Paragraph("Department: " + safe(employee.getDepartment()), normalFont));
            document.add(new Paragraph("Designation: " + safe(employee.getDesignation()), normalFont));
            document.add(new Paragraph("Joining Date: " + safe(employee.getJoinDate()), normalFont));
            document.add(Chunk.NEWLINE);

            document.add(new Paragraph("Approval Details", headingFont));
            document.add(new Paragraph("Reviewed By: " + safe(application.getReviewedBy()), normalFont));
            document.add(new Paragraph("Review Comment: " + safe(application.getReviewComment()), normalFont));
            document.add(Chunk.NEWLINE);

            document.add(new Paragraph("Authorized HR Signature: ____________________", normalFont));
            document.add(Chunk.NEWLINE);
            document.add(new Paragraph("Generated by HR ERP System at " + LocalDateTime.now().withNano(0), normalFont));

            document.close();

            return filePath;

        } catch (Exception e) {
            throw new BadRequestException("Failed to generate reference letter PDF");
        }
    }

    private String safe(String value) {
        return value == null || value.isBlank() ? "-" : value;
    }
}