spring.application.name=erp-backend

server.port=8081

# DATABASE CONFIG
spring.datasource.url=jdbc:postgresql://localhost:5432/erp_db
spring.datasource.username=postgres
spring.datasource.password=2712
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JACKSON
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false

# =========================
# JWT CONFIG
# =========================
app.jwt.secret=6MsjIQi/x4dhDE+XIoTw+A+FdK/yBsqwB+W+j4H/f7WYVz0cQfN67aEHE2BWLXITXXfnIhhXPbRqKTBa4d2n5Q==
app.jwt.expiration-ms=86400000